### ISSUE TITLE
Somehow alleviate lag?

### ISSUE THREAD

**Issue by SuperDisk** [Spade-Editor/Spade#114]
I don't know if it's just for me, but the editor itself is monstrously "laggy;" that is, when you hover over something (eg. a menu item) it takes .25 seconds or so to light up, which while small is still pretty annoying. 

Drawing with the pencil is a slow affair. All of this wouldn't be much of a problem if the old Paint.JAVA wasn't so speedy; Playing with https://github.com/markbernard/Paint.JAVA, it's swift and normal. The mainline Spade branch is slow. This is especially apparent when drawing on a moderately large image (1024x1024). Paint.JAVA handles it like a champ; Spade chokes.

I suspect WebLAF, since even mousing over GUI stuff it takes a bit for it to actually "respond" graphically. Either that, or I fear it's some added complexity in the core, which might be actually necessary to more complex features.

**Comment by HeroesGrave** [comment]
The old Paint.JAVA didn't have layers for a start.

Also on that branch the undo/redo system was incomplete (well, completely broken) due to the fact we had just switched to a new rendering system using Java2D, which additionally was inaccurate and inconsistent (you should've seen some of the circles it drew).

The new drawing system added since then probably won't be as fast as using Java2D, but it shouldn't be far behind. There may be some weird platform-specific things going on that cause more lag on some systems.

I'm currently investigating whether the way PaintCanvas scales up the image could be causing extra lag.

**Comment by HeroesGrave** [comment]
Have you tried exporting and running outside of Eclipse?

For some strange reason that gives me a massive boost to performance.

**Comment by HeroesGrave** [comment]
I finally found the source of the lag.

In all of my timings, I never once included the painting of the transparent background, and funnily enough, that was the source of the lag. It was taking about 15ms to paint, which is pretty much a full frame at 60fps. Time to look into alternative approaches.

**Comment by BurntPizza** [comment]
Is that this? https://github.com/Spade-Editor/Spade/blob/master/src/heroesgrave/spade/gui/PaintCanvas.java#L359-L367
I always cache that kind of thing as a hidden layer or tile a small image to fill the bg.
Also probably reset the paint to whatever it was before if that affects the drawGrid section.

**Comment by HeroesGrave** [comment]
Yep. It's that little piece there.

**Comment by BurntPizza** [comment]
I typically avoid setPaint [for repeated calls], most paints seem pretty inefficient.

**Comment by BurntPizza** [comment]
I also recommend separating paint() into submethods, as that will allow a profiler to tell you exactly where the time is being spent.

**Comment by HeroesGrave** [comment]
Fixed. Uploading new build shortly.

**Comment by BurntPizza** [comment]
Consider keeping in mind to refactor large methods into calling multiple smaller ones in general, paint() stood out especially because it is over 3 pages on github+my monitor.
IDEA would actually have probably issued a complexity warning.

**Comment by HeroesGrave** [comment]
I split it up a little bit, into `composeImage` (draw the layers onto one image), `renderImage` (draw the image to the canvas), and `drawGrid` (self-explanatory).

`composeImage` could probably be split up a little bit further but that's a job for another day.

**Comment by SuperDisk** [comment]
Sweet; What is the performance increase exactly? I'm not seeing the new commit.

**Comment by HeroesGrave** [comment]
Just committed then. Be aware I have just semi-broken plugin versioning. You now need to use `X.Y.Z` or `X.Y.Z-SOME_TEXT`.

Performance varied a bit before but now on a single layered 512^2 image, frames vary between 10 and 15 ms when drawing. Each additional layer should add less than a millisecond and I haven't tested how image size affects things.

**Comment by SuperDisk** [comment]
Hey, hate to kill the buzz but it's still monstrously laggy for me. I suspect it's some form of buffering; Each update of a Change re-renders the entire image when it really should only update a rectangle of interest. I'll get on that when I have some free time.

**Comment by HeroesGrave** [comment]
Hmm, that is weird. At the very least it is still a major performance improvement. We just might need some more.

Try profiling and see where the bottleneck is, now that I've separated the rendering into several functions.
