### ISSUE TITLE
Retina Display Support

### ISSUE THREAD

**Issue by hughrawlinson** [Spade-Editor/Spade#32]
I'll see what I can do for this...

**Comment by hughrawlinson** [comment]
Closing this as this ticket is very old and the project seems pretty inactive, so I'm pruning my created issues.

**Comment by HeroesGrave** [comment]
I'm working on-and-off on a new image editor project (in Rust, not Java), but yeah, Spade is pretty dead.

Java just isn't suited to this sort of thing.

**Comment by SuperDisk** [comment]
A sad day indeed. My solution was just to keep reapplying for free trials of Photoshop... there is seriously nothing better on OS X. (Pixelmator is expensive, Gimp just won't load, Pinta sucks.)

Somebody really should step up and make something good.

**Comment by Longor1996** [comment]
@HeroesGrave I've got a bunch of ideas for a image editor, should I send them to you?

**Comment by HeroesGrave** [comment]
@Longor1996 Sure. Open a new issue if you want.

**Comment by Longor1996** [comment]
@HeroesGrave in the issue tracker of the Spade repository? Or is there a repository for your new project?

**Comment by hughrawlinson** [comment]
Something like Processing might be suited to building an image editor, and that's built on top of Java. If you do want to switch away from the Java ecosystem, I think Elm (or more generally, web) would work well. Canvas is pretty mature, there's a lot of functionality built in, and you can just extend that as a library and then stick a UI on top of it and you're done. Good luck to you all with any future efforts! :)

**Comment by SuperDisk** [comment]
The truth is Java is just too slow to do pixel manipulation. Given, in my attempts to port over the Paint.NET effects to Spade I didn't try anything like parallelization but regular Java is no match for unsafe C# blocks.

A suitable avenue might be a JS & web implementation with canvas running on electron or whatever, but that's pretty huge runtime and frankly pretty dorky.

**Comment by Longor1996** [comment]
@SuperDisk can you do some benchmarks? I'd really like to know just how much of a performance difference there is between C# and Java when comes to image manipulation.

**Comment by SuperDisk** [comment]
Sure. 

It's practically no contest though, as the PDN algorithms that I ported were originally written in unsafe blocks that actually operated on pointers. I rewrote them in Java to operate on regular old arrays and it's a huge slowdown.

The repo is available on my profile if you want to check it out.
